// make_book.cpp : builds cFishFish2/BookData.h from tools/book_lines.txt.
//
// For each "source | SAN line": parse and replay it (illegal / unreadable
// moves end the line), score every position along it with a depth-limited
// search, and cut the line before the first move leading to a position
// scored beyond +/-MaxImbalance (White's view). Writes the surviving lines
// as UCI move strings.
//
//   make_book <book_lines.txt> <out BookData.h> [depth=8] [max_cp=150]

#include <cstdio>
#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include "../cFishFish2/uci.h"

static int score_white_view(const chess::Board& b, int depth, search::TranspositionTable& tt) {
    tt.clear();
    int score = 0;
    search::Hooks h;
    h.should_stop = [](std::uint64_t) { return false; };
    h.start_next_iteration = [&](int d) { return d <= depth; };
    h.report = [&](int, int, int, const search::Line& l, std::uint64_t, int) { score = l.score; };
    search::Searcher s(b, tt, h);
    if (s.iterate({}, 1).best == chess::Move::NO_MOVE) return 0;
    return b.sideToMove() == chess::Color::WHITE ? score : -score;
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        fprintf(stderr, "usage: make_book <book_lines.txt> <BookData.h> [depth] [max_cp]\n");
        return 1;
    }
    const int depth = argc > 3 ? std::atoi(argv[3]) : 8;
    const int max_cp = argc > 4 ? std::atoi(argv[4]) : 150;

    std::ifstream in(argv[1]);
    search::TranspositionTable tt(16);
    std::vector<std::pair<std::string, std::string>> out;  // (source, uci line)
    std::set<std::string> seen;
    int lines = 0, bad_moves = 0, truncated = 0, total_plies = 0, kept_plies = 0;

    for (std::string row; std::getline(in, row);) {
        if (row.empty() || row[0] == '#') continue;
        const auto bar = row.find('|');
        if (bar == std::string::npos) continue;
        std::string source = row.substr(0, bar);
        source.erase(source.find_last_not_of(' ') + 1);
        std::istringstream is(row.substr(bar + 1));
        ++lines;

        chess::Board board;
        std::string uci_line, tok;
        int plies = 0;
        bool cut = false;
        while (is >> tok) {
            if (std::isdigit(static_cast<unsigned char>(tok[0]))) continue;  // "12."
            ++total_plies;
            const chess::Move m = uci::find_san_move(board, tok);
            if (m == chess::Move::NO_MOVE) {
                fprintf(stderr, "  unreadable move '%s' in: %s\n", tok.c_str(), row.c_str());
                ++bad_moves;
                cut = true;
                break;
            }
            chess::Board next = board;
            next.makeMove(m);
            const int s = score_white_view(next, depth, tt);
            if (std::abs(s) > max_cp) {
                fprintf(stderr, "  cut at %s (%+d cp): %s\n", tok.c_str(), s, row.c_str());
                ++truncated;
                cut = true;
                break;
            }
            board = next;
            uci_line += (uci_line.empty() ? "" : " ") + chess::uci::moveToUci(m);
            ++plies;
        }
        (void)cut;
        kept_plies += plies;
        if (!uci_line.empty() && seen.insert(uci_line).second) out.emplace_back(source, uci_line);
    }

    FILE* f = std::fopen(argv[2], "w");
    std::fprintf(f,
                 "// BookData.h : opening book lines for Book.h. GENERATED by tools/make_book\n"
                 "// from tools/book_lines.txt; edit that file and regenerate instead.\n"
                 "//\n"
                 "// Sources: Lichess chess-openings list (CC0, github.com/lichess-org/chess-openings)\n"
                 "// and curated main lines. Every line was replayed for legality and cut before\n"
                 "// any position a depth-%d search scored beyond +/-%d cp.\n\n"
                 "#pragma once\n\n#include <string_view>\n\nnamespace book {\n\n"
                 "inline constexpr std::string_view BookLines[] = {\n",
                 depth, max_cp);
    for (const auto& [src, line] : out) std::fprintf(f, "    \"%s\",  // %s\n", line.c_str(), src.c_str());
    std::fprintf(f, "};\n\n}  // namespace book\n");
    std::fclose(f);

    std::printf("lines %d -> %zu written; plies %d -> %d kept; truncated %d, unreadable %d\n", lines,
                out.size(), total_plies, kept_plies, truncated, bad_moves);
}
